export interface IDictItem {
    label: string
    description: string
}

export const dictionary: IDictItem[] = [
    {label: "30", description: "I have no more to send"},
    {label: "73", description: "Best regards"},
    {label: "88", description: "Love and kisses"},
    {label: "AA", description: "All after"},
    {label: "AB", description: "All before"},
    {label: "AM", description: "Amplitude modulation"},
    {label: "BK", description: "Break, break-in"},
    {label: "BN", description: "All between; been"},
    {label: "BT", description: "Separation (add a space)"},
    {label: "B4", description: "Before"},
    {label: "C", description: "Yes, correct"},
    {label: "CK", description: "Check"},
    {label: "CL", description: "I am closing my station; call"},
    {label: "CQ", description: "Calling any station"},
    {label: "CU", description: "See you"},
    {label: "DA", description: "Day"},
    {label: "DE", description: "From; this is"},
    {label: "DN", description: "Down"},
    {label: "DR", description: "Dear"},
    {label: "DX", description: "Distance"},
    {label: "EL", description: "Element"},
    {label: "ES", description: "And"},
    {label: "FB", description: "Excellent"},
    {label: "FM", description: "Frequency modulation; from"},
    {label: "GA", description: "Go ahead; good afternoon"},
    {label: "GB", description: "Goodbye"},
    {label: "GD", description: "Good"},
    {label: "GE", description: "Good evening"},
    {label: "GG", description: "Going"},
    {label: "GM", description: "Good morning"},
    {label: "GN", description: "Good night"},
    {label: "GV", description: "Give"},
    {label: "HH", description: "Error in sending"},
    {label: "HI", description: "The telegraph laugh; high"},
    {label: "HQ", description: "Headquarters"},
    {label: "HR", description: "Here; hear"},
    {label: "HV", description: "Have"},
    {label: "HW", description: "How, how copy?"},
    {label: "LV", description: "Leave"},
    {label: "MA", description: "Milliamperes"},
    {label: "N", description: "No; negative; incorrect"},
    {label: "ND", description: "Nothing doing"},
    {label: "NM", description: "No more"},
    {label: "NR", description: "Number"},
    {label: "NW", description: "Now; I resume transmission"},
    {label: "OB", description: "Old boy"},
    {label: "OC", description: "Old chap"},
    {label: "OM", description: "Old man"},
    {label: "OP", description: "Operator"},
    {label: "OT", description: "Oldtimer; old top"},
    {label: "PT", description: "Point"},
    {label: "PX", description: "Press"},
    {label: "R", description: "Received as transmitted; are; decimal point"},
    {label: "RC", description: "Ragchew"},
    {label: "RE", description: "Concerning; regarding"},
    {label: "RX", description: "Receive, receiver"},
    {label: "SS", description: "Sweepstakes"},
    {label: "T", description: "Zero"},
    {label: "TR", description: "Transmit"},
    {label: "T", description: "- Transmit/receive"},
    {label: "TT", description: "That"},
    {label: "TU", description: "Thank you"},
    {label: "TX", description: "Transmitter; transmit"},
    {label: "U", description: "You"},
    {label: "VY", description: "Very"},
    {label: "W", description: "Watts"},
    {label: "WA", description: "Word after"},
    {label: "WB", description: "Word before"},
    {label: "WD", description: "Word"},
    {label: "WL", description: "Well; will"},
    {label: "WX", description: "eather"},
    {label: "YL", description: "Young lady"},
    {label: "YR", description: "Year"},
    {label: "ABT", description: "About"},
    {label: "ADEE", description: "Addressee"},
    {label: "ADR", description: "Address"},
    {label: "AGN", description: "Again"},
    {label: "ANT", description: "Antenna"},
    {label: "BCI", description: "Broadcast interference"},
    {label: "BCL", description: "Broadcast listener"},
    {label: "BCNU", description: "Be seeing you"},
    {label: "BTR", description: "Better"},
    {label: "BUG", description: "Semi-automatic key"},
    {label: "CFM", description: "Confirm; I confirm"},
    {label: "CLBK", description: "Callbook"},
    {label: "CLD", description: "Called"},
    {label: "CLG", description: "Calling"},
    {label: "CNT", description: "Can't"},
    {label: "CONDX", description: "Conditions"},
    {label: "CKT", description: "Circuit"},
    {label: "CUL", description: "See you later"},
    {label: "CUM", description: "Come"},
    {label: "DIFF", description: "Difference"},
    {label: "DLD", description: "Delivered"},
    {label: "DLVD", description: "Delivered"},
    {label: "FER", description: "For"},
    {label: "GND", description: "Ground"},
    {label: "GUD", description: "Good"},
    {label: "GESS", description: "Guess"},
    {label: "GVG", description: "Giving"},
]
